# Generated by Django 2.0 on 2018-01-05 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'groups',
                'verbose_name': 'group',
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('dns_name', models.CharField(db_index=True, max_length=64, unique=True)),
                ('ip_address', models.GenericIPAddressField(protocol='IPv4', unique=True)),
                ('description', models.TextField()),
                ('last_seen', models.DateTimeField(null=True)),
                ('synchronization_period', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name_plural': 'hosts',
                'verbose_name': 'host',
            },
        ),
        migrations.CreateModel(
            name='HostStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'host statuses',
                'verbose_name': 'host status',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controller.Group')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controller.Host')),
            ],
            options={
                'verbose_name_plural': 'memberships',
                'verbose_name': 'membership',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField()),
                ('configuration', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'modules',
                'verbose_name': 'module',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64)),
                ('description', models.TextField(null=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controller.Module')),
            ],
            options={
                'verbose_name_plural': 'tasks',
                'verbose_name': 'task',
            },
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'task statuses',
                'verbose_name': 'task status',
            },
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='controller.TaskStatus'),
        ),
        migrations.AddField(
            model_name='task',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controller.Host'),
        ),
        migrations.AddField(
            model_name='host',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='controller.HostStatus'),
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(through='controller.Membership', to='controller.Host'),
        ),
    ]
