# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 21:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupassignment',
            old_name='Group_ID',
            new_name='group_id',
        ),
        migrations.RenameField(
            model_name='groupassignment',
            old_name='Host_ID',
            new_name='host_id',
        ),
        migrations.RenameField(
            model_name='groups',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='groups',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='hosts',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='hosts',
            old_name='DNS_Name',
            new_name='dns_name',
        ),
        migrations.RenameField(
            model_name='hosts',
            old_name='IP_Address',
            new_name='ip_address',
        ),
        migrations.RenameField(
            model_name='hosts',
            old_name='Last_Seen',
            new_name='last_seen',
        ),
        migrations.RenameField(
            model_name='hosts',
            old_name='Status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='hosts',
            old_name='Synchronization_Period',
            new_name='synchronization_period',
        ),
        migrations.RenameField(
            model_name='modules',
            old_name='Configuration',
            new_name='configuration',
        ),
        migrations.RenameField(
            model_name='modules',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='modules',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='statuses',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='statuses',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='Module',
            new_name='module',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='Worker',
            new_name='worker',
        ),
    ]
