# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0002_auto_20171106_2103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupassignment',
            options={'verbose_name': 'host <-> groupa', 'verbose_name_plural': 'host <-> groupa'},
        ),
        migrations.AlterModelOptions(
            name='groups',
            options={'verbose_name': 'grupa', 'verbose_name_plural': 'grupy'},
        ),
        migrations.AlterModelOptions(
            name='hosts',
            options={'verbose_name': 'host', 'verbose_name_plural': 'hosty'},
        ),
        migrations.AlterModelOptions(
            name='modules',
            options={'verbose_name': 'moduł', 'verbose_name_plural': 'moduły'},
        ),
        migrations.AlterModelOptions(
            name='statuses',
            options={'verbose_name': 'status', 'verbose_name_plural': 'statusy'},
        ),
        migrations.AlterModelOptions(
            name='tasks',
            options={'verbose_name': 'zadanie', 'verbose_name_plural': 'zadania'},
        ),
        migrations.AlterField(
            model_name='hosts',
            name='last_seen',
            field=models.DateTimeField(null=True),
        ),
    ]
