# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 23:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0003_auto_20171116_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosts',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='controller.Statuses'),
        ),
    ]
