# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 20:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0003_task_completed'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Statuse',
            new_name='Status',
        ),
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='controller.Status'),
        ),
    ]
