# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0004_auto_20171116_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosts',
            name='ip_address',
            field=models.GenericIPAddressField(protocol='IPv4', unique=True),
        ),
    ]
