# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0005_auto_20171204_2105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'group', 'verbose_name_plural': 'groups'},
        ),
        migrations.AlterModelOptions(
            name='host',
            options={'verbose_name': 'host', 'verbose_name_plural': 'hosts'},
        ),
        migrations.AlterModelOptions(
            name='hoststatus',
            options={'verbose_name': 'host status', 'verbose_name_plural': 'host statuses'},
        ),
        migrations.AlterModelOptions(
            name='membership',
            options={'verbose_name': 'membership', 'verbose_name_plural': 'memberships'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'verbose_name': 'module', 'verbose_name_plural': 'modules'},
        ),
        migrations.AlterModelOptions(
            name='taskstatus',
            options={'verbose_name': 'task status', 'verbose_name_plural': 'task statuses'},
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
